apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-alfa2beta-co-uk
spec:
  secretName: k8s-alfa2beta-co-uk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-alfa2beta.co.uk
  dnsNames:
    - k8s-alfa2beta.co.uk
    - www.k8s-alfa2beta.co.uk